### ISSUE TITLE
Provide boilerplate for changing plain slide text size

### ISSUE THREAD

**Issue by nealmcb** [malikoth/cookiecutter-remarkjs#1]
Thanks for providing some nice examples in the `slides.css` file of how to change presentation text.

For those who don't know much about remark or css, it would help to also document changing the size of fonts in plain slide content.  This seems like it works to me, but I'm also curious to understand more.  E.g. why are you using em's instead of pixels?

```css
.remark-slide-content {
    font-size: 1.5em;
}
```
